### ISSUE TITLE
KG of is_opposite_of assertions

### ISSUE THREAD

**Issue by bill-baumgartner** [NCATSTranslator/opposites#6]
Goals for the May Relay include distribution of known is_opposite_of assertions to the Translator community via a knowledge graph, or incorporation of the assertions into an existing KG (perhaps the Ontology KP).

- [ ] KG serving opposite assertions
   - [x] [Opposite assertions between HP classes](https://github.com/drseb/phenopposites/blob/master/opposites/antonyms_HP.txt) identified by [Köhler et al.](https://www.biorxiv.org/content/10.1101/108977v1.full.pdf)
   - [ ] [Opposite assertions between MP classes](https://github.com/drseb/phenopposites/blob/master/opposites/antonyms_MP.txt) identified by [Köhler et al.](https://www.biorxiv.org/content/10.1101/108977v1.full.pdf)
   - [x] Preliminary opposite assertions between PATO classes discovered via Kevin C's lexical methodology
   - [x] Preliminary opposite assertions between HP classes discovered via Kevin C's lexical methodology
   - [x] Preliminary opposite assertions between classes discovered via Kevin C's lexical methodology in some other ontologies (list TBD)

**Comment by bill-baumgartner** [comment]
@balhoff  For the Spring relay we set a goal to make available some initial results of efforts to catalog opposite ontology classes. I am wondering about how best to disseminate this information. It seems to me that the Ontology KP would be a logical spot to place these assertions. Do you agree? If so, when would you need the data in order to incorporate it by the start of the relay (May 10th), and would an n-triples file suffice in regards to format?  Feel free to suggest an alternative if you think this information should go elsewhere. Thanks!

**Comment by balhoff** [comment]
I think this would work in the Ontology KP. We would need a mapping in biolink-model (skos:exactMatch or skos:narrowMatch) to `http://purl.obolibrary.org/obo/RO_0002604`, if that isn't already there. We would load the n-triples into [Ubergraph](https://github.com/INCATools/ubergraph). The load process takes a couple of days typically.

**Comment by balhoff** [comment]
We have HP opposites loaded already, but it looks like I need to update the biolink-model included in Ubergraph. It doesn't know about the `biolink:opposite_of` predicate.

**Comment by bill-baumgartner** [comment]
@balhoff I just posted an [n-triples file containing lexically-derived assertions of oppositeness](https://raw.githubusercontent.com/NCATSTranslator/opposites/main/assertions/results/lexically-derived-opposites/lexically-derived-opposites.nt) based on @KevinBretonnelCohen's work and manually vetted by @mikebada. Is there still time to load these assertions into Ubergraph prior to the relay? No worries if not. I can load them into one of our KGs temporarily if necessary. Thanks.

**Comment by balhoff** [comment]
I will try to start a load today, thanks.

**Comment by balhoff** [comment]
@bill-baumgartner does your file already include these? https://github.com/INCATools/ubergraph/blob/c56e343f740d6d888a94f81c2317679eaed3648c/Makefile#L44-L45

**Comment by bill-baumgartner** [comment]
@balhoff, No it does not include that file explicitly though there may be some overlap. Would it be helpful to include results from that file?

**Comment by balhoff** [comment]
No, it's not necessary.

**Comment by balhoff** [comment]
These are live now in Ubergraph and Ontology-KP.

**Comment by bill-baumgartner** [comment]
Thanks again @balhoff!
